### PR TITLE
Update `http` documentation links to `https`

### LINKED ISSUE #2152: Convert `http` documentation links to `https`
There are many links to external documentation and specifications contained in the ServiceTalk source code. Many of these links are currently `http` links where they could be `https` links. For example, all links to `http://reactivex.io/documentation` could be upgraded to `https`.

Converting all existing `http` links to `https` within the ServiceTalk source will require checking to ensure that `https` links are available for the content. It will also be a good opportunity to ensure that the links used refer to the canonical path for the referenced material. i.e. ensuring that the link does not redirect to a different preferred location.

### PR DESCRIPTION
**Pull request by domcorvasce**
This PR updates various `http` links found in the project documentation.
Yeah, I know, very low priority but an excuse for me to look around the codebase 😅.

Some clarifications:
- it does **not** affect the project code or tests suite.
- the licensing links were left untouched.
- the links updates have been split in separate commits so changes are easier to inspect.

Closes #2152

### CODE REVIEW

**Comment by domcorvasce** [comment]
Whoops, I’m gonna take care of the linting errors later today :thu

**Comment by domcorvasce** [comment]
It should be fine now. It's always due to `LineLength` 😅

**Comment by bondolo** [comment]
The reactive manifesto url check seems to be a transient problem. As of a few days ago the link was working: https://web.archive.org/web/20220528071924/https://www.reactivemanifesto.org/

**Comment by domcorvasce** [comment]
@bondolo yep, looks like we nailed the timing there.

So I guess we have three choices:
- either link to the archived version of that website
- link to a Wikipedia page (e.g. the reactive programming one)
- link to an external resource (e.g. https://www.oreilly.com/radar/reactive-programming-vs-reactive-systems/)

 I think the first one makes the most sense given that - although I don't want to jinx it - archive.org is pretty reliable. What do you think?

P.S: I pushed the archived version of that link. I can always revert it back if you want to go ahead with other options.

**Comment by bondolo** [comment]
@domcorvasce Thank you for the updates. For the moment I am assuming that the outage on `reactivemanifesto.org` is temporary and we can continue to use the link.

**Comment by bondolo** [comment]
The [reactive manifesto](https://www.reactivemanifesto.org/) site seems to be functioning normally again. Can we switch the link back to a direct link?

**Review by bondolo — APPROVED** [review]

**Pull request merged**
