### PR TITLE
Gradle wrapper validation

### PR DESCRIPTION
**Pull request by sullis**
https://blog.gradle.org/gradle-wrapper-checksum-verification-github-action

### CODE REVIEW

**Comment by NiteshKant** [comment]
@servicetalk-bot test this please

**Comment by sullis** [comment]
ping @NiteshKant

**Comment by NiteshKant** [comment]
@idelpivnitskiy you ok with this?

**Review by idelpivnitskiy — APPROVED** [review]
Yep, looks great,
Thanks @sullis!

**Pull request merged**
