### PR TITLE
ConcurrentStack prevent duplicate concurrent terminals

### PR DESCRIPTION
**Pull request by Scottmitch**
Motivation:
ConcurrentStack doesn't strictly enforce a single terminal signal will
be processed unless there is external synchronization. The Subscriber
APIs don't allow for concurrent invocation, and require external
synchronization, but we can provide this capability to be safe.

Modifications:
- Rename ConcurrentStack -> ClosableConcurrentStack
- ClosableConcurrentStack to track terminal state upon the close
operation, and return it for subsequent push attempts.

Result:
CompletableProcessor and CompletableSingle protect against concurrent
terminal notifications.

### CODE REVIEW

**Comment by Scottmitch** [comment]
https://github.com/apple/servicetalk/pull/1283#discussion_r546185550

the extra memory barriers adds overhead in multithreaded cases, however it still is an improvement over what we had originally with the concurrent queue.

```
# non-atomic terminal (prior to this PR)
CompletableProcessorBenchmark.mtAdd20Complete  thrpt    5    951658.114 ±  15566.060  ops/s

# atomic terminal (with volatile coordination between threads)
CompletableProcessorBenchmark.mtAdd20Complete  thrpt    5    715757.301 ±  22471.221  ops/s 
```

**Comment by Scottmitch** [comment]
test failure due to https://github.com/apple/servicetalk/issues/1224

**Comment by Scottmitch** [comment]
test failure due to https://github.com/apple/servicetalk/issues/1299

**Review by idelpivnitskiy — COMMENTED** [review]
Thanks for the follow-up!
I started to write review comments, but then played with the code and prepared them as a patch:
```patch
Index: servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SingleProcessor.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SingleProcessor.java	(revision 07a11b65e4684514d3412b0dcb51e6ed361a13b7)
+++ servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SingleProcessor.java	(date 1608413666073)
@@ -28,8 +28,7 @@
  * @param <T> The type of result of the {@link Single}.
  */
 final class SingleProcessor<T> extends Single<T> implements Processor<T, T> {
-    private final ClosableStateConcurrentStack<Subscriber<? super T>, Consumer<Subscriber<? super T>>> stack =
-            new ClosableStateConcurrentStack<>();
+    private final ClosableStateConcurrentStack<Subscriber<? super T>> stack = new ClosableStateConcurrentStack<>();
 
     @Override
     protected void handleSubscribe(final Subscriber<? super T> subscriber) {
@@ -67,7 +66,7 @@
     }
 
     private void terminate(Consumer<Subscriber<? super T>> terminalSignal) {
-        stack.close(terminalSignal, terminalSignal);
+        stack.close(terminalSignal);
     }
 
     @Override
Index: servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CompletableProcessor.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CompletableProcessor.java	(revision 07a11b65e4684514d3412b0dcb51e6ed361a13b7)
+++ servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CompletableProcessor.java	(date 1608413666076)
@@ -20,6 +20,8 @@
 import io.servicetalk.concurrent.internal.DelayedCancellable;
 import io.servicetalk.concurrent.internal.TerminalNotification;
 
+import java.util.function.Consumer;
+
 import static io.servicetalk.concurrent.internal.TerminalNotification.complete;
 
 /**
@@ -27,8 +29,7 @@
  * the {@link Subscriber} methods which is forwarded to all existing or subsequent {@link Subscriber}s.
  */
 final class CompletableProcessor extends Completable implements Processor {
-    private final ClosableStateConcurrentStack<Subscriber, TerminalNotification> stack =
-            new ClosableStateConcurrentStack<>();
+    private final ClosableStateConcurrentStack<Subscriber> stack = new ClosableStateConcurrentStack<>();
 
     @Override
     protected void handleSubscribe(Subscriber subscriber) {
@@ -38,15 +39,15 @@
         // we would add the subscriber to the queue and possibly never (until termination) dereference the subscriber.
         DelayedCancellable delayedCancellable = new DelayedCancellable();
         subscriber.onSubscribe(delayedCancellable);
-        TerminalNotification terminalNotification = stack.push(subscriber);
-        if (terminalNotification == null) {
+        Consumer<Subscriber> terminalSignal = stack.push(subscriber);
+        if (terminalSignal == null) {
             delayedCancellable.delayedCancellable(() -> {
                 // Cancel in this case will just cleanup references from the queue to ensure we don't prevent GC of
                 // these references.
                 stack.relaxedRemove(subscriber);
             });
         } else {
-            terminalNotification.terminate(subscriber);
+            terminalSignal.accept(subscriber);
         }
     }
 
@@ -66,7 +67,7 @@
     }
 
     private void terminate(TerminalNotification terminalSignal) {
-        stack.close(terminalSignal::terminate, terminalSignal);
+        stack.close(terminalSignal::terminate);
     }
 
     @Override
Index: servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/ClosableConcurrentStackTest.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/ClosableConcurrentStackTest.java	(revision 07a11b65e4684514d3412b0dcb51e6ed361a13b7)
+++ servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/ClosableConcurrentStackTest.java	(date 1608450040155)
@@ -26,8 +26,9 @@
 
 import static io.servicetalk.concurrent.api.Single.collectUnordered;
 import static org.hamcrest.MatcherAssert.assertThat;
+import static org.hamcrest.Matchers.empty;
+import static org.hamcrest.Matchers.is;
 import static org.hamcrest.Matchers.isIn;
-import static org.junit.Assert.assertEquals;
 
 public class ClosableConcurrentStackTest {
     @ClassRule
@@ -44,9 +45,9 @@
         List<Integer> values = new ArrayList<>(itemCount);
         stack.close(values::add);
 
-        assertEquals(itemCount, values.size());
+        assertThat(values.size(), is(itemCount));
         for (int i = itemCount - 1; i >= 0; --i) {
-            assertEquals(values.get(itemCount - i - 1).intValue(), i);
+            assertThat(values.get(itemCount - i - 1), is(i));
         }
     }
 
@@ -78,9 +79,18 @@
                 overallValues.add(integer);
             }
         }
-        assertEquals(itemCount, overallValues.size());
+        assertThat(overallValues.size(), is(itemCount));
         for (int i = 0; i < itemCount; ++i) {
             assertThat(i, isIn(overallValues));
         }
     }
+
+    @Test
+    public void closeEmpty() {
+        ClosableConcurrentStack<Integer> stack = new ClosableConcurrentStack<>();
+        List<Integer> values = new ArrayList<>();
+        stack.close(values::add);
+        assertThat(values, is(empty()));
+        assertThat(stack.push(-1), is(false));
+    }
 }
Index: servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ClosableConcurrentStack.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ClosableConcurrentStack.java	(revision 07a11b65e4684514d3412b0dcb51e6ed361a13b7)
+++ servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ClosableConcurrentStack.java	(date 1608415213643)
@@ -46,6 +46,7 @@
     }
 
     void close(Consumer<T> closer) {
+        requireNonNull(closer);
         @SuppressWarnings("unchecked")
         Node<T> oldTop = topUpdater.getAndSet(this, closedNode());
         if (oldTop == CLOSED) {
Index: servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/ClosableStateConcurrentStackTest.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/ClosableStateConcurrentStackTest.java	(revision 07a11b65e4684514d3412b0dcb51e6ed361a13b7)
+++ servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/ClosableStateConcurrentStackTest.java	(date 1608449923567)
@@ -25,15 +25,14 @@
 import java.util.List;
 import java.util.concurrent.CyclicBarrier;
 import java.util.concurrent.Future;
+import java.util.function.Consumer;
 
 import static io.servicetalk.concurrent.api.Completable.mergeAll;
 import static io.servicetalk.concurrent.api.Single.collectUnordered;
 import static org.hamcrest.MatcherAssert.assertThat;
 import static org.hamcrest.Matchers.empty;
 import static org.hamcrest.Matchers.is;
-import static org.junit.Assert.assertEquals;
-import static org.junit.Assert.assertNull;
-import static org.junit.Assert.assertTrue;
+import static org.hamcrest.Matchers.nullValue;
 import static org.mockito.Mockito.mock;
 import static org.mockito.Mockito.verify;
 
@@ -43,7 +42,7 @@
 
     @Test
     public void singleThreadPushClose() {
-        ClosableConcurrentStack<Integer> stack = new ClosableConcurrentStack<>();
+        ClosableStateConcurrentStack<Integer> stack = new ClosableStateConcurrentStack<>();
         final int itemCount = 1000;
         for (int i = 0; i < itemCount; ++i) {
             stack.push(i);
@@ -52,29 +51,29 @@
         List<Integer> values = new ArrayList<>(itemCount);
         stack.close(values::add);
 
-        assertEquals(itemCount, values.size());
+        assertThat(values.size(), is(itemCount));
         for (int i = itemCount - 1; i >= 0; --i) {
-            assertEquals(values.get(itemCount - i - 1).intValue(), i);
+            assertThat(values.get(itemCount - i - 1), is(i));
         }
     }
 
     @Test
     public void singleThreadPushRemove() {
-        ClosableStateConcurrentStack<Integer, String> stack = new ClosableStateConcurrentStack<>();
+        ClosableStateConcurrentStack<Integer> stack = new ClosableStateConcurrentStack<>();
         final int itemCount = 1000;
         for (int i = 0; i < itemCount; ++i) {
             stack.push(i);
         }
 
         for (int i = 0; i < itemCount; ++i) {
-            assertTrue(stack.relaxedRemove(i));
+            assertThat(stack.relaxedRemove(i), is(true));
         }
         closeAssertEmpty(stack);
     }
 
     @Test
     public void concurrentPushRemove() throws Exception {
-        ClosableStateConcurrentStack<Integer, String> stack = new ClosableStateConcurrentStack<>();
+        ClosableStateConcurrentStack<Integer> stack = new ClosableStateConcurrentStack<>();
         final int itemCount = 1000;
         CyclicBarrier barrier = new CyclicBarrier(itemCount + 1);
         List<Completable> completableList = new ArrayList<>(itemCount);
@@ -86,8 +85,8 @@
                 } catch (Exception e) {
                     throw new AssertionError(e);
                 }
-                assertNull(stack.push(finalI));
-                assertTrue("failed for index: " + finalI, stack.relaxedRemove(finalI));
+                assertThat(stack.push(finalI), nullValue());
+                assertThat("failed for index: " + finalI, stack.relaxedRemove(finalI), is(true));
             }));
         }
 
@@ -99,7 +98,7 @@
 
     @Test
     public void concurrentPushRemoveDifferentThread() throws Exception {
-        ClosableStateConcurrentStack<Integer, String> stack = new ClosableStateConcurrentStack<>();
+        ClosableStateConcurrentStack<Integer> stack = new ClosableStateConcurrentStack<>();
         final int itemCount = 1000;
         CyclicBarrier barrier = new CyclicBarrier(itemCount + 1);
         List<Completable> completableList = new ArrayList<>(itemCount);
@@ -113,7 +112,7 @@
                 }
                 stack.push(finalI);
             }).concat(EXECUTOR_RULE.executor().submit(() ->
-                    assertTrue("failed for index: " + finalI, stack.relaxedRemove(finalI)))));
+                    assertThat("failed for index: " + finalI, stack.relaxedRemove(finalI), is(true)))));
         }
 
         Future<Void> future = mergeAll(completableList, itemCount).toFuture();
@@ -124,7 +123,7 @@
 
     @Test
     public void concurrentClosePushRemove() throws Exception {
-        ClosableStateConcurrentStack<Cancellable, String> stack = new ClosableStateConcurrentStack<>();
+        ClosableStateConcurrentStack<Cancellable> stack = new ClosableStateConcurrentStack<>();
         final int itemCount = 1000;
         CyclicBarrier barrier = new CyclicBarrier(itemCount + 1);
         List<Single<Cancellable>> completableList = new ArrayList<>(itemCount);
@@ -136,7 +135,7 @@
                 } catch (Exception e) {
                     throw new AssertionError(e);
                 }
-                assertNull(stack.push(c));
+                assertThat(stack.push(c), nullValue());
                 return c;
             }));
         }
@@ -144,17 +143,24 @@
         Future<Collection<Cancellable>> future = collectUnordered(completableList, itemCount).toFuture();
         barrier.await();
         Collection<Cancellable> cancellables = future.get();
-        stack.close(Cancellable::cancel, "closed");
-        assertEquals("closed", stack.push(() -> { }));
+        Consumer<Cancellable> closer = Cancellable::cancel;
+        stack.close(closer);
+        assertThat(stack.push(() -> { }), is(closer));
         for (Cancellable c : cancellables) {
             verify(c).cancel();
         }
     }
 
-    private static void closeAssertEmpty(ClosableStateConcurrentStack<Integer, String> stack) {
+    @Test
+    public void closeEmpty() {
+        closeAssertEmpty(new ClosableStateConcurrentStack<>());
+    }
+
+    private static void closeAssertEmpty(ClosableStateConcurrentStack<Integer> stack) {
         List<Integer> values = new ArrayList<>();
-        stack.close(values::add, "foo");
+        Consumer<Integer> closer = values::add;
+        stack.close(closer);
         assertThat(values, is(empty()));
-        assertEquals("foo", stack.push(-1));
+        assertThat(stack.push(-1), is(closer));
     }
 }
Index: servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ClosableStateConcurrentStack.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ClosableStateConcurrentStack.java	(revision 07a11b65e4684514d3412b0dcb51e6ed361a13b7)
+++ servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ClosableStateConcurrentStack.java	(date 1608451481912)
@@ -24,7 +24,7 @@
 import static java.util.Objects.requireNonNull;
 import static java.util.concurrent.atomic.AtomicReferenceFieldUpdater.newUpdater;
 
-final class ClosableStateConcurrentStack<T, C> {
+final class ClosableStateConcurrentStack<T> {
     @SuppressWarnings("rawtypes")
     private static final AtomicReferenceFieldUpdater<ClosableStateConcurrentStack, Object> topUpdater =
             newUpdater(ClosableStateConcurrentStack.class, Object.class, "top");
@@ -34,17 +34,17 @@
     /**
      * Push an item onto the stack.
      * @param item the item to push onto the stack.
-     * @return {@code null} if the operation was successful. Otherwise the state from {@link #close(Consumer, Object)}
+     * @return {@code null} if the operation was successful. Otherwise the state from {@link #close(Consumer)}
      * if this stack has been closed.
      */
     @SuppressWarnings("unchecked")
     @Nullable
-    C push(T item) {
+    Consumer<T> push(T item) {
         final Node<T> newTop = new Node<>(item);
         for (;;) {
             final Object rawOldTop = top;
             if (rawOldTop != null && !Node.class.equals(rawOldTop.getClass())) {
-                return (C) rawOldTop;
+                return (Consumer<T>) rawOldTop;
             }
             newTop.next = (Node<T>) rawOldTop;
             if (topUpdater.compareAndSet(this, rawOldTop, newTop)) {
@@ -60,12 +60,13 @@
      * this method means {@code true} might be returned in the following scenarios without external synchronization:
      * <ul>
      *     <li>invoked multiple times with the same {@code item} from different threads</li>
-     *     <li>{@link #close(Consumer, Object)} removes this item from another thread</li>
+     *     <li>{@link #close(Consumer)} removes this item from another thread</li>
      * </ul>
      */
     boolean relaxedRemove(T item) {
+        requireNonNull(item);
         final Object rawCurrTop = top;
-        if (item == null || rawCurrTop == null || !Node.class.equals(rawCurrTop.getClass())) {
+        if (rawCurrTop == null || !Node.class.equals(rawCurrTop.getClass())) {
             return false;
         }
         @SuppressWarnings("unchecked")
@@ -85,18 +86,16 @@
      * Clear the stack contents, and prevent future {@link #push(Object)} operations from adding to this stack.
      * {@code closer} will be invoked for each element currently in the stack.
      * @param closer Invoked for each element currently in the stack. Elements that were previously
-     * {@link #relaxedRemove(Object) relaxRemoved} may still invoked by {@code closer}.
-     * @param state The state to return for future {@link #push(Object)} calls, which indicates this stack has been
-     * closed.
+     * {@link #relaxedRemove(Object) relaxRemoved} may still invoked by {@code closer}. The {@code closer} will be used
+     * as return value for future {@link #push(Object)} calls, which indicates this stack has been closed.
      */
-    void close(Consumer<T> closer, C state) {
+    void close(Consumer<T> closer) {
         requireNonNull(closer);
-        requireNonNull(state); // push returns null for success or this state if closed, so it can't be null.
         Object rawOldTop;
         for (;;) {
             rawOldTop = top;
             if (rawOldTop == null || Node.class.equals(rawOldTop.getClass())) {
-                if (topUpdater.compareAndSet(this, rawOldTop, state)) {
+                if (topUpdater.compareAndSet(this, rawOldTop, closer)) {
                     break;
                 }
             } else {
```
LMK what you think.

**Comment by Scottmitch** [comment]
@idelpivnitskiy - sounds reasonable. I consolidated the stack implementations for now too. there is a perf difference due to the "state" version having to do some additional reference/class checks, but for now I think it is OK.

**Review by idelpivnitskiy — APPROVED** [review]
LG!

**Pull request merged**
