### PR TITLE
Revert "Deprecate `IoExecutor` create w/ `ThreadFactory` (#1738)"

### PR DESCRIPTION
**Pull request by Scottmitch**
Motivation:
japicmp.sh revealed some API breakage [1].

[1]
```
***! MODIFIED CLASS: PUBLIC NON_FINAL (<- FINAL) io.servicetalk.transport.netty.internal.IoThreadFactory  (not serializable)
	===  CLASS FILE FORMAT VERSION: 52.0 <- 52.0
	---! REMOVED INTERFACE: java.util.concurrent.ThreadFactory
	===  UNCHANGED SUPERCLASS: java.lang.Object (<- java.lang.Object)
```

Modifications:
- Revert 441f907bf32e2f0d2086067f75ecf118664fcf79

Result:
Avoid API breakage, which can be corrected in a followup PR.

### CODE REVIEW

**Review by idelpivnitskiy — APPROVED** [review]
👍

**Comment by Scottmitch** [comment]
build failure attributed to https://github.com/apple/servicetalk/issues/1507

**Comment by Scottmitch** [comment]
build failure attributed to https://github.com/apple/servicetalk/issues/1579

**Comment by Scottmitch** [comment]
build failure attributed to https://github.com/apple/servicetalk/issues/1579

**Pull request merged**
